### ISSUE TITLE
submit_answer function errors when it shouldn't

### ISSUE THREAD

**Issue by miguelraz** [heetbeet/project-euler-julia#2]
```

julia> submit_answer(104_743, prob_num=7)
[ Info: Your answer is 104743
  ⚠️ Oops, wrong answer!

```

**Comment by miguelraz** [comment]
Additional feature request:
`clipboard(answer` just before the correct answer returns the congratulations string so that pasting it into the site is easier.

**Comment by heetbeet** [comment]
Fixed with the following hashing function

```
function do_hash(x::Number)
    sha1(reinterpret(UInt8, [Float64(x)])) |> join
end


function do_hash(x)
    sha1(x) |> join
end
```

**Comment by heetbeet** [comment]
![image](https://user-images.githubusercontent.com/4103775/111042906-4c724100-8448-11eb-93f3-307e502b3d43.png)

https://github.com/heetbeet/project-euler-julia/commit/9ddcbbc188f42eeed0849c6e7d1d678ddca61757

**Comment by miguelraz** [comment]
Beautiful! All works now. Thanks a lot!

**Comment by heetbeet** [comment]
@miguelraz I noticed that only the first Pluto notebook worked correctly. The others somehow got the UUID of all the puzzles leaked into the Pluto structure with Pluto complaining. I also fixed that
